kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
        - name: app
          image: quay.io/rh_ee_ssheri/notes-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: public
