kind: Secret
apiVersion: v1
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRESQL_ADMIN_PASSWORD: cG9zdGdyZXM=
  POSTGRESQL_PASSWORD: cG9zdGdyZXM=
  POSTGRESQL_DATABASE: bm90ZXNkYg==
  POSTGRESQL_USER: U29rb2wK
