kind: Deployment
apiVersion: apps/v1
metadata:
  name: psql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: registry.redhat.io/rhel8/postgresql-12:1-109.1655143367
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: public
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRESQL_ADMIN_PASSWORD
                  optional: false
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRESQL_PASSWORD
                  optional: false
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRESQL_DATABASE
                  optional: false
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRESQL_USER
                  optional: false
